gitlabUrl: http://gitlab-webservice-default:8181
runnerRegistrationToken: "glrt-1RJ9mHL9MXhR9K4kmyVCeW86MQpwOjEKdDozCnU6MQ8.01.171if0t7d" 

rbac:
  create: true

serviceAccount:
  create: true

runners:
  config: |
    [[runners]]
      executor = "kubernetes"
      clone_url = "http://gitlab-webservice-default:8181"
      [runners.kubernetes]
        privileged = true 